sudo: required
services:
  - docker

before_install:
  - docker build -t frontend:test -f Dockerfile.dev .

script:
  - docker run frontend:test npm run test -- --coverage --forceExit --detectOpenHandles --maxWorkers=10
