version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  react-app-test:
    command: ["npm", "run", "test"]
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    